server:
  port: 8443 
  ssl:    enabled: true
    key-store: src/main/resources/security-jwt.p12
    key-store-password: security-jwt
    key-store-type: PKC512 
    key-alias: security-jwt
  servlet:    context-path: / 


spring:  datasource:    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt?serverTimezone=UTC&useSSL=false
    username: cos
    password: bitc5600
  jpa:    open-in-view: false
    hibernate:      ddl-auto: create
      naming:        physical-strategy: org.hibernate.boot.moder.naming.PhysicalNamingStrategyStandardImp1
    show-sql: true
    properties:      hibernate.format_sql: true           